### ISSUE TITLE
[优化请求] 私人文章不出现在  RSS 订阅页

### ISSUE THREAD

**Issue by linsein** [bigshans/hugo-blog#1]
我觉得您的文章很有价值，所以订阅了您博客的 RSS 页面。  
但满怀欣喜的看到有新文章，准备阅读时，发现是打不开的“私人文章”，会觉得有些失望。过多的私人文章出现在 RSS 订阅列表里也会觉得有点被打扰。  

故请求在 RSS 生成规则里过滤去除掉私人文章。  

我的博客的 RSS 输出中，使用了如下的生成规则，去除掉包含 “NoRSS: true" 参数的文章，希望能有参考价值：
```
{{ range first 10 (where .Site.RegularPages "Params.NoRSS" "!=" true) }}
<item> .... </item>
{{ end }}
```

**Comment by bigshans** [comment]
好的，已经修改了。现在的 rss 里面已经不会出现私人文章了。感谢你的订阅。
